# #+TITLE: Spacemacs
#+BEGIN_CENTER
[[http://spacemacs.org][file:https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]]
#+END_CENTER

* P’undrak’s dotfiles

This is my collection of dotfiles for my daily GNU/Linux environment, tweaked to my liking. If you wish to get these dotfiles, follow the [[*Installation][installation guide]].

As you can see, I personally use [[https://github.com/zsh-users/zsh][zsh]] as my shell of choice, and [[https://github.com/emacs-mirror/emacs][Emacs]] using [[http://spacemacs.org/][Spacemacs]] (still with Emacs keybinding) as my editor of choice.

I also use as my desktop environment [[https://github.com/Airblader/i3][i3-gaps]] + [[https://github.com/jaagr/polybar][polybar]] + [[https://github.com/chjj/compton][compton]]. You will find some screenshot below.

** Features

- Handy zsh aliases
- Ready to use Emacs dotfiles optimized for C, Modern C++, Python and Java development
- Ready to use i3 dotfiles

** Dependencies

Because indeed there are some dependencies, and here they are. The versions mentionned are the version I am currently using. My dotfiles *might* work with earlier versions.
- [[https://github.com/emacs-mirror/emacs][Emacs]] >= ~25.3-1~
  -  [[http://spacemacs.org/][Spacemacs]] >= ~0.200.9@25.3.1~
- [[https://github.com/zsh-users/zsh][zsh]] >= ~5.0~
- ~.zshrc~ dependencies (can be ignored if commenting out the corresponding lines in the file):
  + [[https://github.com/powerline/powerline][powerline]] >= ~2.6-1~
  + [[http://clang.llvm.org/][clang]] >= ~5.0.0-1~
  + [[http://www.andre-simon.de/doku/highlight/highlight.html][highlight]] >= ~3.39-1~
  + [[http://rg3.github.io/youtube-dl][youtube-dl]] >= ~2017.10.01-1~
  + [[https://curl.haxx.se][curl]] >= ~7.55.1-2~
  + [[https://github.com/dylanaraps/neofetch][neofetch]] >= ~3.2.1~
  + [[https://feh.finalrewind.org/][feh]] >= ~2.20-1~
- [[https://github.com/Airblader/i3][i3-gaps]] >= ~4.14.1-1~
- [[https://github.com/chjj/compton][compton]] >= ~0.1_beta2.5-8~
- [[https://github.com/dylanaraps/pywal][pywal]] >= ~0.6.9-1~
- [[http://tools.suckless.org/dmenu/][dmenu]] >= ~4.7-1~
- [[http://invisible-island.net/xterm/][uxterm]] >= ~330-1~
- [[https://rustup.rs/][Rust nightly]] >= ~0.20~
- [[https://eclipse.org][eclipse-common]] >= ~4.7.1-1~
- [[https://eclipse.org][eclipse-java]] >= ~4.7.1-1~
- [[https://eclipse.org][eclipse-pydev]] >= ~5.9.2-1~
- [[http://eclim.org/install.html][eclim]]
- [[http://tug.org/texlive][texlive-core]] >= ~2017.44918-1~
- [[https://github.com/gpoore/minted][minted]] >= ~2.5-1~

Please notice that all of my package manager commands are made for ~pacman~ (Arch Linux); if you do not use this package manager, do not forget to comment out the related lines in ~.zshrc~.

** Installation

To install the dotfiles, you have two options. You can either:
- replace your original dotfiles with mine in their original place.
- create symbolic links to the dotfiles in the folder where they were downloaded.

The advantage with the latter is you will have all the dotfiles in the same place, plus if at one point you want to get updates from the dotfiles, you just have to download them again at the same place and you won’t have to bother placing them again at the right place.

In any case, if you want to use my dotfiles for Emacs, *please install Spacemacs first*.

** Licence

All of my dotfiles (and my dotfiles only) are available under the GNU GPLv3 Licence. Please consult [[https://github.com/Phundrak/dotfiles/blob/master/LICENSE.md][LICENCE.md]] for more information. In short: you are free to access, edit and redistribute all of my dotfiles under the same licence and as allowed by the licence, and if you fuck up something, it’s your own responsibility.
